[phases.setup]
aptPkgs = [
  "chromium",
  "libnss3",
  "libatk-bridge2.0-0",
  "libdrm2",
  "libxcomposite1",
  "libxdamage1",
  "libxrandr2",
  "libgbm1",
  "libasound2",
  "libpangocairo-1.0-0",
  "libgtk-3-0",
  "libxshmfence1",
  "fonts-liberation",
  "fonts-noto-color-emoji"
]

[variables]
PUPPETEER_SKIP_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
